version: '3'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: liquid_loading_api
    ports:
      - "7999:7999"
    volumes:
      - ../config:/app/config
      - ../data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7999/health"]
      interval: 30s
      timeout: 10s
      retries: 3 